"""
100-Class Municipal Grievance Taxonomy and Semantic Knowledge Base
Maps R01-R10, W01-W10, S01-S10, D01-D10, E01-E10, P01-P10, B01-B10, T01-T10, H01-H10, A01-A10
to 10 Municipal Departments with multilingual training examples.
"""
from typing import Dict, Any, List

DEPARTMENTS_10 = [
    {"id": "PWD", "code": "PWD", "name": "Roads & PWD", "jurisdiction": "Potholes, road damage, footpaths, road construction, and utility trench restoration.", "contact_email": "pwd-roads@city.gov.in"},
    {"id": "WATER", "code": "WATER", "name": "Water Supply", "jurisdiction": "Drinking water supply, leaks, contamination, low pressure, and pipeline repairs.", "contact_email": "water-helpline@city.gov.in"},
    {"id": "SWM", "code": "SWM", "name": "Sanitation & Solid Waste", "jurisdiction": "Garbage collection, sweeping, overflowing bins, and debris disposal.", "contact_email": "sanitation-swm@city.gov.in"},
    {"id": "DRAINAGE", "code": "DRAINAGE", "name": "Drainage & Stormwater", "jurisdiction": "Street waterlogging, choked drains, sewage overflow, and open manholes.", "contact_email": "drainage-cell@city.gov.in"},
    {"id": "ELECTRICAL", "code": "ELECTRICAL", "name": "Electrical & Street Lighting", "jurisdiction": "Streetlights, power outages, dark roads, transformer sparks, and live wire hazards.", "contact_email": "electrical-cell@city.gov.in"},
    {"id": "GARDEN", "code": "GARDEN", "name": "Parks & Public Spaces", "jurisdiction": "Public parks, tree trimming, garden benches, playground equipment, and green spaces.", "contact_email": "parks-garden@city.gov.in"},
    {"id": "ENCROACHMENT", "code": "ENCROACHMENT", "name": "Municipal Engineering & Buildings", "jurisdiction": "Illegal construction, building encroachments, dangerous structures, and unauthorized building.", "contact_email": "building-engineering@city.gov.in"},
    {"id": "TRAFFIC", "code": "TRAFFIC", "name": "Traffic & Transport", "jurisdiction": "Traffic congestion, illegal parking, bus stops, traffic signals, and pedestrian safety.", "contact_email": "traffic-transport@city.gov.in"},
    {"id": "HEALTH", "code": "HEALTH", "name": "Public Health", "jurisdiction": "Mosquito breeding/fogging, food safety, unhygienic premises, disease risk, and public nuisance.", "contact_email": "public-health@city.gov.in"},
    {"id": "ANIMAL_CONTROL", "code": "ANIMAL_CONTROL", "name": "Animal Control", "jurisdiction": "Stray dogs, aggressive animals, injured animals, dead animal removal, and stray cattle.", "contact_email": "animal-control@city.gov.in"}
]

TAXONOMY_100: Dict[str, Dict[str, Any]] = {
    # 1. Roads & PWD (R01 - R10)
    "R01": {"class_id": "R01", "class_name": "Pothole", "department_id": "PWD", "department_name": "Roads & PWD", "severity": "High", "keywords": ["pothole", "potholes", "gaddha", "khadda", "deep crater", "sadak pe gaddha", "road crater", "bike slip", "pothole hazard", "road hole"]},
    "R02": {"class_id": "R02", "class_name": "Damaged Road", "department_id": "PWD", "department_name": "Roads & PWD", "severity": "High", "keywords": ["damaged road", "sadak tooti", "broken road", "rough road", "tar washed away", "road not repaired", "road restoration after pipeline", "dug up road", "sadak khod ke", "bad road", "road repair", "road broken", "asphalt damaged"]},
    "R03": {"class_id": "R03", "class_name": "Road Cracks", "department_id": "PWD", "department_name": "Roads & PWD", "severity": "Medium", "keywords": ["road cracks", "cracks on asphalt", "fissures on road", "darar", "tar cracking", "asphalt cracks"]},
    "R04": {"class_id": "R04", "class_name": "Damaged Footpath", "department_id": "PWD", "department_name": "Roads & PWD", "severity": "Medium", "keywords": ["damaged footpath", "broken sidewalk", "footpath tiles broken", "paver blocks broken", "footpath toota", "broken footpath", "pavement broken"]},
    "R05": {"class_id": "R05", "class_name": "Road Obstruction", "department_id": "PWD", "department_name": "Roads & PWD", "severity": "High", "keywords": ["road obstruction", "road blocked by material", "gravel on road", "construction material on road", "sadak par rukaavat", "stones on road"]},
    "R06": {"class_id": "R06", "class_name": "Missing Road Sign", "department_id": "PWD", "department_name": "Roads & PWD", "severity": "Low", "keywords": ["missing road sign", "signboard missing", "no direction board", "speed limit board missing", "signage broken", "road sign"]},
    "R07": {"class_id": "R07", "class_name": "Damaged Road Divider", "department_id": "PWD", "department_name": "Roads & PWD", "severity": "High", "keywords": ["damaged road divider", "median broken", "broken divider", "divider crash", "divider toota", "road median damaged"]},
    "R08": {"class_id": "R08", "class_name": "Damaged Speed Breaker", "department_id": "PWD", "department_name": "Roads & PWD", "severity": "Medium", "keywords": ["damaged speed breaker", "broken speed breaker", "speed bump broken", "unmarked speed breaker", "rumble strip damaged", "speed breaker"]},
    "R09": {"class_id": "R09", "class_name": "Road Flooding", "department_id": "PWD", "department_name": "Roads & PWD", "severity": "Critical", "keywords": ["road flooding", "submerged road", "highway flooded", "road underwater", "sadak dharasai"]},
    "R10": {"class_id": "R10", "class_name": "Road Construction Hazard", "department_id": "PWD", "department_name": "Roads & PWD", "severity": "Critical", "keywords": ["road construction hazard", "unbarricaded road work", "open trench on road", "missing barricades", "trench left open", "open trench"]},

    # 2. Water Supply (W01 - W10)
    "W01": {"class_id": "W01", "class_name": "No Water Supply", "department_id": "WATER", "department_name": "Water Supply", "severity": "Critical", "keywords": ["no water supply", "paani nahi aa raha", "pani nahi hai", "water supply stopped", "dry taps", "nal sukha", "water cut", "no water", "drinking water not coming", "tap dry"]},
    "W02": {"class_id": "W02", "class_name": "Low Water Pressure", "department_id": "WATER", "department_name": "Water Supply", "severity": "Medium", "keywords": ["low water pressure", "kam pressure", "slow water coming", "low pressure tap", "water pressure issue", "slow tap water", "pressure low"]},
    "W03": {"class_id": "W03", "class_name": "Water Pipeline Leakage", "department_id": "WATER", "department_name": "Water Supply", "severity": "High", "keywords": ["water pipeline leakage", "pipe leaking", "clean water leak", "water pipe burst", "paani beh raha", "pipe leak", "water leak", "pipeline leaking"]},
    "W04": {"class_id": "W04", "class_name": "Contaminated Water", "department_id": "WATER", "department_name": "Water Supply", "severity": "Critical", "keywords": ["contaminated water", "not clean water", "dirty water", "unclean water", "muddy water", "smelly water", "yellow water", "black water", "ganda paani", "dushit paani", "water smells bad", "bad taste water", "smelly and yellow", "smelly", "dirty tap water", "unclean drinking water", "bad water", "foul water"]},
    "W05": {"class_id": "W05", "class_name": "Broken Water Pipeline", "department_id": "WATER", "department_name": "Water Supply", "severity": "Critical", "keywords": ["broken water pipeline", "main pipe burst", "pipeline rupture", "main water line broken", "water pipe tut gaya", "burst water pipe", "broken pipeline"]},
    "W06": {"class_id": "W06", "class_name": "Irregular Water Supply", "department_id": "WATER", "department_name": "Water Supply", "severity": "Medium", "keywords": ["irregular water supply", "water timing erratic", "untimed water", "supply not on schedule", "paani ka time fix nahi", "erratic water supply"]},
    "W07": {"class_id": "W07", "class_name": "Water Wastage", "department_id": "WATER", "department_name": "Water Supply", "severity": "Medium", "keywords": ["water wastage", "tanki overflow", "public tap overflowing", "water running continuously", "paani barbaad", "wasting water"]},
    "W08": {"class_id": "W08", "class_name": "Damaged Water Valve", "department_id": "WATER", "department_name": "Water Supply", "severity": "High", "keywords": ["damaged water valve", "water valve broken", "valve leaking", "control valve damaged", "water valve"]},
    "W09": {"class_id": "W09", "class_name": "Illegal Water Connection", "department_id": "WATER", "department_name": "Water Supply", "severity": "High", "keywords": ["illegal water connection", "water theft", "illegal water pipe tapping", "chori ka paani connection"]},
    "W10": {"class_id": "W10", "class_name": "Water Tanker Issue", "department_id": "WATER", "department_name": "Water Supply", "severity": "Medium", "keywords": ["water tanker issue", "tanker not arrived", "water tanker delay", "tanker pricing fraud", "water tanker"]},

    # 3. Sanitation & Solid Waste (S01 - S10)
    "S01": {"class_id": "S01", "class_name": "Garbage Accumulation", "department_id": "SWM", "department_name": "Sanitation & Solid Waste", "severity": "High", "keywords": ["garbage accumulation", "garbage heap", "kachra jama", "trash accumulation", "kuda dhair", "garbage pile", "garbage", "trash pile", "kachra"]},
    "S02": {"class_id": "S02", "class_name": "Missed Garbage Collection", "department_id": "SWM", "department_name": "Sanitation & Solid Waste", "severity": "Medium", "keywords": ["missed garbage collection", "garbage vehicle not arrived", "kachra gadi nahi aayi", "unpicked trash", "door to door waste missed", "garbage not collected"]},
    "S03": {"class_id": "S03", "class_name": "Overflowing Garbage Bin", "department_id": "SWM", "department_name": "Sanitation & Solid Waste", "severity": "High", "keywords": ["overflowing garbage bin", "dustbin overflow", "kudedaan bhara hua", "bin full spilling", "overflowing trash can", "dustbin", "overflowing bin"]},
    "S04": {"class_id": "S04", "class_name": "Illegal Garbage Dumping", "department_id": "SWM", "department_name": "Sanitation & Solid Waste", "severity": "High", "keywords": ["illegal garbage dumping", "dumping waste on road", "open dumping", "unauthorized garbage dump", "kachra phekna", "dumping garbage"]},
    "S05": {"class_id": "S05", "class_name": "Open Garbage Site", "department_id": "SWM", "department_name": "Sanitation & Solid Waste", "severity": "High", "keywords": ["open garbage site", "uncovered waste dump", "open dhalav", "stinking open trash", "open dump"]},
    "S06": {"class_id": "S06", "class_name": "Construction Waste", "department_id": "SWM", "department_name": "Sanitation & Solid Waste", "severity": "Medium", "keywords": ["construction waste", "debris dumped", "malba pada hai", "c&d waste", "rubble on street", "debris"]},
    "S07": {"class_id": "S07", "class_name": "Plastic Waste Accumulation", "department_id": "SWM", "department_name": "Sanitation & Solid Waste", "severity": "Medium", "keywords": ["plastic waste accumulation", "single use plastic dump", "plastic bags littered", "polythene waste", "plastic waste"]},
    "S08": {"class_id": "S08", "class_name": "Unclean Public Area", "department_id": "SWM", "department_name": "Sanitation & Solid Waste", "severity": "Medium", "keywords": ["unclean public area", "street sweeping not done", "safai nahi hui", "dirty street", "uncleaned pavement", "sweeping not done", "safai"]},
    "S09": {"class_id": "S09", "class_name": "Waste Collection Vehicle Issue", "department_id": "SWM", "department_name": "Sanitation & Solid Waste", "severity": "Low", "keywords": ["waste collection vehicle issue", "garbage truck broken", "ghanta gadi issue", "waste truck smoke", "garbage truck"]},
    "S10": {"class_id": "S10", "class_name": "Dead Animal Waste Disposal", "department_id": "SWM", "department_name": "Sanitation & Solid Waste", "severity": "Critical", "keywords": ["dead animal waste disposal", "carcass disposal", "mrit janwar safai", "dead animal carcass removal", "dead animal waste"]},

    # 4. Drainage & Stormwater (D01 - D10)
    "D01": {"class_id": "D01", "class_name": "Blocked Drain", "department_id": "DRAINAGE", "department_name": "Drainage & Stormwater", "severity": "High", "keywords": ["blocked drain", "choked drain", "drain jam", "nala choke", "drain blocked with silt", "gutter blocked", "choked gutter"]},
    "D02": {"class_id": "D02", "class_name": "Overflowing Drain", "department_id": "DRAINAGE", "department_name": "Drainage & Stormwater", "severity": "High", "keywords": ["overflowing drain", "gutter overflowing", "ganda paani sadak pe", "gutter spill", "drain overflow", "gutter overflow", "overflowing gutter"]},
    "D03": {"class_id": "D03", "class_name": "Waterlogging", "department_id": "DRAINAGE", "department_name": "Drainage & Stormwater", "severity": "High", "keywords": ["waterlogging", "water logging", "water logged", "paani bhara", "jal jamaav", "water in front of house", "stagnant water", "water logging on road"]},
    "D04": {"class_id": "D04", "class_name": "Flooded Street", "department_id": "DRAINAGE", "department_name": "Drainage & Stormwater", "severity": "Critical", "keywords": ["flooded street", "street flood", "gully flood", "rasta duba", "monsoon flood street", "flooding"]},
    "D05": {"class_id": "D05", "class_name": "Damaged Drain", "department_id": "DRAINAGE", "department_name": "Drainage & Stormwater", "severity": "Medium", "keywords": ["damaged drain", "broken gutter wall", "nala collapsed", "drain structural damage", "drain broken"]},
    "D06": {"class_id": "D06", "class_name": "Open Manhole", "department_id": "DRAINAGE", "department_name": "Drainage & Stormwater", "severity": "Critical", "keywords": ["open manhole", "khula manhole", "manhole lid missing", "missing drain cover", "khula dhakkan", "manhole hazard", "manhole open"]},
    "D07": {"class_id": "D07", "class_name": "Sewage Overflow", "department_id": "DRAINAGE", "department_name": "Drainage & Stormwater", "severity": "Critical", "keywords": ["sewage overflow", "sewer line backup", "toilet sewage on road", "foul sewer spill", "sewerage choke", "sewage", "sewer overflow"]},
    "D08": {"class_id": "D08", "class_name": "Drainage Bad Odour", "department_id": "DRAINAGE", "department_name": "Drainage & Stormwater", "severity": "Medium", "keywords": ["drainage bad odour", "stinking drain", "gutter smell", "nala badboo", "foul drain odor", "drain smell"]},
    "D09": {"class_id": "D09", "class_name": "Clogged Stormwater Channel", "department_id": "DRAINAGE", "department_name": "Drainage & Stormwater", "severity": "High", "keywords": ["clogged stormwater channel", "storm drain clogged", "monsoon drain blocked", "culvert clogged", "stormwater"]},
    "D10": {"class_id": "D10", "class_name": "Broken Drain Cover", "department_id": "DRAINAGE", "department_name": "Drainage & Stormwater", "severity": "High", "keywords": ["broken drain cover", "cracked manhole slab", "damaged chamber lid", "dhakkan toota", "drain cover broken"]},

    # 5. Electrical & Street Lighting (E01 - E10)
    "E01": {"class_id": "E01", "class_name": "Streetlight Not Working", "department_id": "ELECTRICAL", "department_name": "Electrical & Street Lighting", "severity": "High", "keywords": ["streetlight not working", "street light band", "batti band", "light not glowing", "defunct street light", "street lights not working", "street light"]},
    "E02": {"class_id": "E02", "class_name": "Broken Streetlight", "department_id": "ELECTRICAL", "department_name": "Electrical & Street Lighting", "severity": "Medium", "keywords": ["broken streetlight", "light fixture broken", "lamp smashed", "street lamp broken", "broken street lamp"]},
    "E03": {"class_id": "E03", "class_name": "Flickering Streetlight", "department_id": "ELECTRICAL", "department_name": "Electrical & Street Lighting", "severity": "Low", "keywords": ["flickering streetlight", "light blinking", "flickering street lamp", "light jhilmil"]},
    "E04": {"class_id": "E04", "class_name": "Dark Road", "department_id": "ELECTRICAL", "department_name": "Electrical & Street Lighting", "severity": "High", "keywords": ["dark road", "andhera hai", "complete darkness on road", "no lights on street", "pitch dark street", "dark street"]},
    "E05": {"class_id": "E05", "class_name": "Damaged Electric Pole", "department_id": "ELECTRICAL", "department_name": "Electrical & Street Lighting", "severity": "High", "keywords": ["damaged electric pole", "tilted pole", "bent electric pole", "khamba tedha", "pole damaged", "electric pole"]},
    "E06": {"class_id": "E06", "class_name": "Exposed Electrical Wire", "department_id": "ELECTRICAL", "department_name": "Electrical & Street Lighting", "severity": "Critical", "keywords": ["exposed electrical wire", "live wire", "open wire", "taar khula", "wire sparking", "electric shock risk", "open electrical wire"]},
    "E07": {"class_id": "E07", "class_name": "Fallen Electric Pole", "department_id": "ELECTRICAL", "department_name": "Electrical & Street Lighting", "severity": "Critical", "keywords": ["fallen electric pole", "pole collapsed", "electric pole on road", "khamba gir gaya", "fallen pole"]},
    "E08": {"class_id": "E08", "class_name": "Transformer Problem", "department_id": "ELECTRICAL", "department_name": "Electrical & Street Lighting", "severity": "Critical", "keywords": ["transformer problem", "transformer spark", "transformer blast", "transformer smoking", "dp box blast", "transformer"]},
    "E09": {"class_id": "E09", "class_name": "Traffic Signal Malfunction", "department_id": "ELECTRICAL", "department_name": "Electrical & Street Lighting", "severity": "High", "keywords": ["traffic signal malfunction", "traffic light not working", "signal dead", "signal blinking amber", "traffic signal broken"]},
    "E10": {"class_id": "E10", "class_name": "Electrical Safety Hazard", "department_id": "ELECTRICAL", "department_name": "Electrical & Street Lighting", "severity": "Critical", "keywords": ["electrical safety hazard", "power cut", "power outage", "no electricity", "bijli gul", "short circuit", "voltage fluctuation", "shock hazard", "electricity outage"]},

    # 6. Parks & Public Spaces (P01 - P10)
    "P01": {"class_id": "P01", "class_name": "Damaged Park Equipment", "department_id": "GARDEN", "department_name": "Parks & Public Spaces", "severity": "Medium", "keywords": ["damaged park equipment", "broken swing", "broken slide", "jhula toota", "open gym broken", "damaged swing", "playground swing broken", "swing broken", "slide broken"]},
    "P02": {"class_id": "P02", "class_name": "Unmaintained Park", "department_id": "GARDEN", "department_name": "Parks & Public Spaces", "severity": "Medium", "keywords": ["unmaintained park", "garden neglected", "dry park", "park overgrown", "garden safai nahi", "park maintenance"]},
    "P03": {"class_id": "P03", "class_name": "Broken Public Bench", "department_id": "GARDEN", "department_name": "Parks & Public Spaces", "severity": "Low", "keywords": ["broken public bench", "park bench broken", "sitting bench damaged", "bench toota", "broken bench"]},
    "P04": {"class_id": "P04", "class_name": "Overgrown Vegetation", "department_id": "GARDEN", "department_name": "Parks & Public Spaces", "severity": "Medium", "keywords": ["overgrown vegetation", "tree trimming", "dangerous tree branch", "pruning needed", "ped ki dali tooti", "overgrown weeds", "tree branch", "falling tree", "dry tree branch", "tree pruning"]},
    "P05": {"class_id": "P05", "class_name": "Damaged Playground", "department_id": "GARDEN", "department_name": "Parks & Public Spaces", "severity": "Medium", "keywords": ["damaged playground", "play area dangerous", "children play ground damaged", "khelne ki jagah kharab", "playground damaged", "children playground"]},
    "P06": {"class_id": "P06", "class_name": "Poor Park Lighting", "department_id": "GARDEN", "department_name": "Parks & Public Spaces", "severity": "Medium", "keywords": ["poor park lighting", "park lights not working", "dark garden", "garden lights off", "park light"]},
    "P07": {"class_id": "P07", "class_name": "Public Space Encroachment", "department_id": "GARDEN", "department_name": "Parks & Public Spaces", "severity": "High", "keywords": ["public space encroachment", "garden encroachment", "park land encroached", "kabza on park"]},
    "P08": {"class_id": "P08", "class_name": "Public Space Cleanliness", "department_id": "GARDEN", "department_name": "Parks & Public Spaces", "severity": "Medium", "keywords": ["public space cleanliness", "park litter", "bottles in garden", "clean public ground", "garden garbage"]},
    "P09": {"class_id": "P09", "class_name": "Damaged Park Fencing", "department_id": "GARDEN", "department_name": "Parks & Public Spaces", "severity": "Low", "keywords": ["damaged park fencing", "broken boundary wall park", "garden railing broken", "park fence damaged"]},
    "P10": {"class_id": "P10", "class_name": "Unsafe Public Open Space", "department_id": "GARDEN", "department_name": "Parks & Public Spaces", "severity": "High", "keywords": ["unsafe public open space", "anti social elements in park", "dark unsafe ground", "unsecured public open space"]},

    # 7. Municipal Engineering & Buildings (B01 - B10)
    "B01": {"class_id": "B01", "class_name": "Illegal Construction", "department_id": "ENCROACHMENT", "department_name": "Municipal Engineering & Buildings", "severity": "High", "keywords": ["illegal construction", "unauthorized construction", "illegal building", "building without permit", "avadh nirman", "unapproved construction", "illegal structure"]},
    "B02": {"class_id": "B02", "class_name": "Unsafe Building", "department_id": "ENCROACHMENT", "department_name": "Municipal Engineering & Buildings", "severity": "Critical", "keywords": ["unsafe building", "dilapidated building", "building collapse risk", "khatarnaak building", "condemned structure"]},
    "B03": {"class_id": "B03", "class_name": "Building Damage", "department_id": "ENCROACHMENT", "department_name": "Municipal Engineering & Buildings", "severity": "High", "keywords": ["building damage", "balcony broken", "plaster falling", "building facade cracked"]},
    "B04": {"class_id": "B04", "class_name": "Building Encroachment", "department_id": "ENCROACHMENT", "department_name": "Municipal Engineering & Buildings", "severity": "High", "keywords": ["building encroachment", "encroached marginal space", "illegal extension into setback", "kabza on setback"]},
    "B05": {"class_id": "B05", "class_name": "Unauthorized Building Extension", "department_id": "ENCROACHMENT", "department_name": "Municipal Engineering & Buildings", "severity": "High", "keywords": ["unauthorized building extension", "illegal floor added", "illegal rooftop shed", "illegal extension", "floor added"]},
    "B06": {"class_id": "B06", "class_name": "Construction Debris", "department_id": "ENCROACHMENT", "department_name": "Municipal Engineering & Buildings", "severity": "Medium", "keywords": ["construction debris", "builder dumped rubble", "malba left on footpath", "construction material hazard"]},
    "B07": {"class_id": "B07", "class_name": "Dangerous Structure", "department_id": "ENCROACHMENT", "department_name": "Municipal Engineering & Buildings", "severity": "Critical", "keywords": ["dangerous structure", "falling wall", "unsupported wall", "scaffolding collapsed", "dangerous wall"]},
    "B08": {"class_id": "B08", "class_name": "Footpath Encroachment", "department_id": "ENCROACHMENT", "department_name": "Municipal Engineering & Buildings", "severity": "High", "keywords": ["footpath encroachment", "hawkers on sidewalk", "illegal shop on footpath", "kabza on footpath", "footpath blocked by vendors", "illegal shop", "hawkers blocking", "footpath blocked"]},
    "B09": {"class_id": "B09", "class_name": "Structural Cracks", "department_id": "ENCROACHMENT", "department_name": "Municipal Engineering & Buildings", "severity": "Critical", "keywords": ["structural cracks", "pillar cracks", "beam cracked", "building foundation cracks", "pillar crack"]},
    "B10": {"class_id": "B10", "class_name": "Construction Safety Hazard", "department_id": "ENCROACHMENT", "department_name": "Municipal Engineering & Buildings", "severity": "Critical", "keywords": ["construction safety hazard", "no safety nets at construction", "falling bricks hazard", "unsecured construction site"]},

    # 8. Traffic & Transport (T01 - T10)
    "T01": {"class_id": "T01", "class_name": "Traffic Congestion", "department_id": "TRAFFIC", "department_name": "Traffic & Transport", "severity": "High", "keywords": ["traffic congestion", "traffic jam", "heavy jam", "traffic choke point", "jam laga hai", "traffic jam"]},
    "T02": {"class_id": "T02", "class_name": "Illegal Parking", "department_id": "TRAFFIC", "department_name": "Traffic & Transport", "severity": "Medium", "keywords": ["illegal parking", "no parking violation", "double parking", "cars parked blocking road", "illegal parked vehicle", "wrong parking"]},
    "T03": {"class_id": "T03", "class_name": "Abandoned Vehicle", "department_id": "TRAFFIC", "department_name": "Traffic & Transport", "severity": "Medium", "keywords": ["abandoned vehicle", "junk car on street", "abandoned rusted scooter", "khatara gaadi", "abandoned car"]},
    "T04": {"class_id": "T04", "class_name": "Missing Traffic Sign", "department_id": "TRAFFIC", "department_name": "Traffic & Transport", "severity": "Low", "keywords": ["missing traffic sign", "no U-turn board missing", "one way sign missing", "traffic board absent"]},
    "T05": {"class_id": "T05", "class_name": "Traffic Signal Problem", "department_id": "TRAFFIC", "department_name": "Traffic & Transport", "severity": "High", "keywords": ["traffic signal problem", "signal timing mismatch", "red light not working", "signal not changing", "traffic light problem"]},
    "T06": {"class_id": "T06", "class_name": "Dangerous Junction", "department_id": "TRAFFIC", "department_name": "Traffic & Transport", "severity": "Critical", "keywords": ["dangerous junction", "accident prone intersection", "blind turn", "khatarnaak chauraha", "dangerous intersection"]},
    "T07": {"class_id": "T07", "class_name": "Bus Stop Problem", "department_id": "TRAFFIC", "department_name": "Traffic & Transport", "severity": "Medium", "keywords": ["bus stop problem", "bus stop shed broken", "bus not stopping at stop", "damaged bus shelter", "bus stop"]},
    "T08": {"class_id": "T08", "class_name": "Roadside Obstruction", "department_id": "TRAFFIC", "department_name": "Traffic & Transport", "severity": "High", "keywords": ["roadside obstruction", "vehicle blocking lane", "commercial vehicle loading on street"]},
    "T09": {"class_id": "T09", "class_name": "Pedestrian Safety Issue", "department_id": "TRAFFIC", "department_name": "Traffic & Transport", "severity": "High", "keywords": ["pedestrian safety issue", "zebra crossing missing", "no pedestrian crossing", "unsafe for walking", "pedestrian safety"]},
    "T10": {"class_id": "T10", "class_name": "Wrong-Way Traffic", "department_id": "TRAFFIC", "department_name": "Traffic & Transport", "severity": "Critical", "keywords": ["wrong-way traffic", "driving on wrong side", "one way violation", "ulta gaadi chala rahe", "wrong side driving"]},

    # 9. Public Health (H01 - H10)
    "H01": {"class_id": "H01", "class_name": "Mosquito Breeding", "department_id": "HEALTH", "department_name": "Public Health", "severity": "High", "keywords": ["mosquito breeding", "mosquito menace", "dengue risk", "malaria prevention", "machhar", "fogging needed", "larvae in water", "mosquito", "dengue", "fogging"]},
    "H02": {"class_id": "H02", "class_name": "Public Health Hazard", "department_id": "HEALTH", "department_name": "Public Health", "severity": "Critical", "keywords": ["public health hazard", "epidemic risk", "swine flu", "biomedical waste dumped", "health hazard", "biomedical waste"]},
    "H03": {"class_id": "H03", "class_name": "Food Hygiene Complaint", "department_id": "HEALTH", "department_name": "Public Health", "severity": "Critical", "keywords": ["food hygiene complaint", "unhygienic restaurant", "expired food", "food adulteration", "food poisoning", "unclean kitchen", "rotten food", "food safety"]},
    "H04": {"class_id": "H04", "class_name": "Unsanitary Premises", "department_id": "HEALTH", "department_name": "Public Health", "severity": "Medium", "keywords": ["unsanitary premises", "unhygienic commercial establishment", "unclean clinic", "unsanitary shop"]},
    "H05": {"class_id": "H05", "class_name": "Stray Animal Health Concern", "department_id": "HEALTH", "department_name": "Public Health", "severity": "High", "keywords": ["stray animal health concern", "rabies risk", "infected animal", "rabid animal", "zoonotic disease"]},
    "H06": {"class_id": "H06", "class_name": "Disease Risk Area", "department_id": "HEALTH", "department_name": "Public Health", "severity": "Critical", "keywords": ["disease risk area", "cholera outbreak risk", "typhoid risk area", "infection hotspot"]},
    "H07": {"class_id": "H07", "class_name": "Sewage Health Hazard", "department_id": "HEALTH", "department_name": "Public Health", "severity": "Critical", "keywords": ["sewage health hazard", "sewage water mixing with soil", "open defecation site", "foul biological hazard"]},
    "H08": {"class_id": "H08", "class_name": "Foul Smell / Public Nuisance", "department_id": "HEALTH", "department_name": "Public Health", "severity": "Medium", "keywords": ["foul smell", "public nuisance", "bad chemical odor", "air pollution nuisance", "pungent smell"]},
    "H09": {"class_id": "H09", "class_name": "Unsafe Drinking Water", "department_id": "HEALTH", "department_name": "Public Health", "severity": "Critical", "keywords": ["unsafe drinking water", "water contamination health alert", "waterborne disease outbreak", "arsenic in water"]},
    "H10": {"class_id": "H10", "class_name": "Public Hygiene Issue", "department_id": "HEALTH", "department_name": "Public Health", "severity": "Medium", "keywords": ["public hygiene issue", "unhygienic public toilet", "sulabh sauchalay dirty", "spitting in public", "dirty public toilet"]},

    # 10. Animal Control (A01 - A10)
    "A01": {"class_id": "A01", "class_name": "Stray Dog", "department_id": "ANIMAL_CONTROL", "department_name": "Animal Control", "severity": "Medium", "keywords": ["stray dog", "street dogs menace", "dog pack in street", "gully ke kutte", "stray dog sterilized", "stray dogs", "kutte"]},
    "A02": {"class_id": "A02", "class_name": "Aggressive Animal", "department_id": "ANIMAL_CONTROL", "department_name": "Animal Control", "severity": "Critical", "keywords": ["aggressive animal", "biting dog", "dog bite incident", "kutte ne kata", "aggressive stray animal", "animal attack", "biting"]},
    "A03": {"class_id": "A03", "class_name": "Injured Animal", "department_id": "ANIMAL_CONTROL", "department_name": "Animal Control", "severity": "High", "keywords": ["injured animal", "injured dog on road", "wounded cow", "ghayal janwar", "hit and run animal", "injured dog"]},
    "A04": {"class_id": "A04", "class_name": "Dead Animal", "department_id": "ANIMAL_CONTROL", "department_name": "Animal Control", "severity": "Critical", "keywords": ["dead animal", "dead dog", "dead cat", "mar gaya janwar", "animal carcass on road", "dead dog on road"]},
    "A05": {"class_id": "A05", "class_name": "Animal Nuisance", "department_id": "ANIMAL_CONTROL", "department_name": "Animal Control", "severity": "Medium", "keywords": ["animal nuisance", "dogs barking all night", "monkeys creating nuisance", "bandar ka aatank", "monkey nuisance"]},
    "A06": {"class_id": "A06", "class_name": "Stray Cattle", "department_id": "ANIMAL_CONTROL", "department_name": "Animal Control", "severity": "High", "keywords": ["stray cattle", "cows on road", "bhais sadak par", "stray bull", "cattle blocking traffic", "stray cows", "cows"]},
    "A07": {"class_id": "A07", "class_name": "Animal Shelter Issue", "department_id": "ANIMAL_CONTROL", "department_name": "Animal Control", "severity": "Low", "keywords": ["animal shelter issue", "gaushala overcrowding", "animal pound issue"]},
    "A08": {"class_id": "A08", "class_name": "Animal Waste", "department_id": "ANIMAL_CONTROL", "department_name": "Animal Control", "severity": "Medium", "keywords": ["animal waste", "dog poop on footpath", "cow dung on road", "gobar road pe"]},
    "A09": {"class_id": "A09", "class_name": "Animal Traffic Hazard", "department_id": "ANIMAL_CONTROL", "department_name": "Animal Control", "severity": "High", "keywords": ["animal traffic hazard", "cattle on highway", "cows causing accident", "animals running into traffic"]},
    "A10": {"class_id": "A10", "class_name": "Illegal Animal Activity", "department_id": "ANIMAL_CONTROL", "department_name": "Animal Control", "severity": "Critical", "keywords": ["illegal animal activity", "illegal slaughter", "animal cruelty", "illegal animal trade"]}
}
